"""Real-component smoke test for ``mcp_common.server.launcher``.

Phase 1 / Task 1.9 of the MCP Launcher Standardization plan
(``mahavishnu/docs/plans/2026-09-26-mcp-launcher-standardization.md``).
Spawns the canonical ``launch(...)`` entry point against a trivial
FastMCP 4.x application, curls ``GET /health`` over HTTP, and asserts
the response is HTTP 200 with a body containing the launcher-version
field.

Run from the repo root::

    .venv/bin/python scripts/launch_smoke.py [port]

Exit codes:
    0 - smoke test passed
    1 - smoke test failed
"""

from __future__ import annotations

import argparse
import json
import os
import socket
import subprocess
import sys
import tempfile
import textwrap
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

# The script intentionally avoids third-party deps (httpx, requests, rich)
# so it runs in the lean mcp-common install without forcing optional
# packages. The launcher itself depends on starlette/uvicorn via fastmcp,
# but those are required for the launcher to work at all.


# Template for the trivial FastMCP app. ``__PORT__`` and ``__VERSION__`` are
# substituted at write time so the spawned process knows where to bind and
# what launcher-version string to embed in the /health body.
APP_TEMPLATE = textwrap.dedent('''\
    """Trivial FastMCP app for the launch_smoke harness.

    Generated by scripts/launch_smoke.py. Imports FastMCP 4.x and the
    canonical launcher from mcp_common, registers a custom /health route
    so the smoke test can verify the launcher-version field, then calls
    ``launch(...)`` to start the HTTP server.
    """

    from __future__ import annotations

    import sys

    from fastmcp import FastMCP
    from starlette.responses import JSONResponse

    from mcp_common import launch

    app = FastMCP(name="launch_smoke")


    @app.custom_route("/health", methods=["GET"])
    async def http_health(request: object) -> JSONResponse:
        """Trivial /health route that surfaces the launcher version.

        The canonical launcher itself does not register /health; each
        component does that via register_http_health_route. We register a
        minimal version here so the smoke harness can assert the
        ``launcher`` field is present end-to-end.
        """
        return JSONResponse(
            {
                "status": "ok",
                "service": "launch_smoke",
                "version": "__VERSION__",
                "launcher": "mcp_common.server.launcher@__VERSION__",
                "checks": [],
            }
        )


    if __name__ == "__main__":
        import asyncio

        # The launcher is the entry point under test; we just supply a
        # zero-arg build_server closure so it stays fully generic.
        asyncio.run(
            launch(
                build_server=lambda: app,
                component_name="launch_smoke",
                host="127.0.0.1",
                port=__PORT__,
            )
        )
        sys.exit(0)
''')


def pick_free_port() -> int:
    """Bind to port 0 to let the kernel assign an unused port.

    The socket is closed before returning so the port is immediately
    reusable. There is a tiny TOCTOU race between close and re-bind by
    the spawned process, but on a localhost-only smoke test that window
    is negligible and re-trying would mask real regressions.
    """
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


def get_launcher_version() -> str:
    """Return the installed mcp-common version (e.g. ``"0.27.0"``).

    Used both to embed in the spawned app's /health body and to assert
    the same version shows up in the actual response. Falls back to
    ``"unknown"`` if the metadata lookup fails so the smoke test still
    produces a clear failure message instead of crashing before launch.
    """
    from importlib.metadata import PackageNotFoundError, version

    try:
        return version("mcp-common")
    except PackageNotFoundError:
        return "unknown"


def wait_for_http(url: str, timeout: float = 20.0) -> tuple[int, str]:
    """Poll ``url`` until it returns HTTP 200 or ``timeout`` elapses.

    Returns the last (status, body) tuple observed. Raises TimeoutError
    if no 200 is seen within the deadline so the caller can surface
    subprocess stderr for debugging.
    """
    deadline = time.monotonic() + timeout
    last_err = "no attempt yet"
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=2.0) as resp:
                body = resp.read().decode("utf-8", errors="replace")
                return int(resp.status), body
        except urllib.error.HTTPError as exc:
            # Server is up but returned non-2xx — record and keep polling
            # briefly in case the server is still warming up.
            last_err = f"HTTP {exc.code}: {exc.reason}"
            body = ""
            try:
                body = exc.read().decode("utf-8", errors="replace")
            except Exception as read_exc:
                # HTTPError.read() can fail (e.g. chunked transfer error); the
                # status code is what matters for the smoke probe. Keep going.
                print(f"warning: could not read HTTP error body: {read_exc}")
            return int(exc.code), body
        except (urllib.error.URLError, ConnectionError, OSError) as exc:
            last_err = f"{type(exc).__name__}: {exc}"
            time.sleep(0.2)
    raise TimeoutError(
        f"GET {url} did not return 200 within {timeout}s (last error: {last_err})"
    )


def main() -> int:
    ap = argparse.ArgumentParser(
        description=(
            "Smoke-test the canonical mcp_common.server.launcher.launch() "
            "against a trivial FastMCP app."
        )
    )
    ap.add_argument(
        "port",
        nargs="?",
        type=int,
        default=None,
        help="Port for the smoke server (default: pick a free port).",
    )
    args = ap.parse_args()

    port: int = args.port or pick_free_port()
    version: str = get_launcher_version()

    # Anchor the venv python path relative to this file (per user policy:
    # never hardcode /Users/les/.../python). Falls back to ``sys.executable``
    # if the local .venv is missing so CI can still run the script.
    repo_root = Path(__file__).resolve().parent.parent
    venv_python = repo_root / ".venv" / "bin" / "python"
    python_exe = str(venv_python) if venv_python.exists() else sys.executable

    app_src = APP_TEMPLATE.replace("__PORT__", str(port)).replace(
        "__VERSION__", version
    )

    with tempfile.TemporaryDirectory() as td:
        tmpdir = Path(td)
        app_path = tmpdir / "launch_smoke_app.py"
        app_path.write_text(app_src, encoding="utf-8")

        proc = subprocess.Popen(
            [python_exe, str(app_path)],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=os.environ.copy(),
        )

        try:
            try:
                status, body = wait_for_http(
                    f"http://127.0.0.1:{port}/health", timeout=20.0
                )
            except TimeoutError as exc:
                stderr = (
                    proc.stderr.read().decode("utf-8", errors="replace")
                    if proc.stderr
                    else ""
                )
                print(f"FAIL: {exc}", file=sys.stderr)
                if stderr.strip():
                    print(f"--- subprocess stderr ---\n{stderr}", file=sys.stderr)
                return 1

            if status != 200:
                print(
                    f"FAIL: expected HTTP 200 from /health, got {status}",
                    file=sys.stderr,
                )
                print(f"body: {body!r}", file=sys.stderr)
                return 1

            # Parse as JSON; fall back to substring check on raw body if
            # the server returned non-JSON for any reason.
            parsed: Any
            try:
                parsed = json.loads(body)
            except json.JSONDecodeError:
                parsed = body

            joined = (
                json.dumps(parsed) if isinstance(parsed, (dict, list)) else str(parsed)
            )

            expected = f'"launcher": "mcp_common.server.launcher@{version}"'
            if expected not in joined:
                print(
                    "FAIL: /health body lacks launcher-version field",
                    file=sys.stderr,
                )
                print(f"  expected substring: {expected!r}", file=sys.stderr)
                print(f"  body: {body!r}", file=sys.stderr)
                return 1

            # Per HealthCheckResponse shape (and our trivial app), the body
            # should also expose a ``checks`` key. The canonical register_*
            # health helpers always emit one — assert it so future drift
            # in /health shape gets caught.
            if isinstance(parsed, dict) and "checks" not in parsed:
                print(
                    "FAIL: /health body lacks 'checks' key",
                    file=sys.stderr,
                )
                print(f"  body: {body!r}", file=sys.stderr)
                return 1

            body_excerpt = body if len(body) <= 240 else body[:240] + "..."
            print(
                f"PASS: /health 200 with launcher-version field at "
                f"http://127.0.0.1:{port}/health"
            )
            print(f"  body: {body_excerpt}")
            return 0
        finally:
            if proc.poll() is None:
                proc.terminate()
                try:
                    proc.wait(timeout=5.0)
                except subprocess.TimeoutExpired:
                    proc.kill()
                    proc.wait()


if __name__ == "__main__":
    sys.exit(main())
